modLoader = "kotlinforforge"
loaderVersion = "[4.10,)"
license = "GPL-3.0-or-later"
issueTrackerURL = "https://github.com/natrow/tfc_minecolonies/issues"

# TFCM
[[mods]]
modId = "tfcm"
version = "${file.jarVersion}"
displayName = "TerraFirmaMineColonies"
displayURL = "https://github.com/natrow/tfc_minecolonies"
logoFile = "tfcm.png"
authors = "natrow"
description = '''Provides handmade compatibility between TerraFirmaCraft and MineColonies'''

# Dependencies
[[dependencies.tfcm]]
modId = "minecolonies"
mandatory = true
versionRange = "[1.1.395-BETA,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.tfcm]]
modId = "tfc"
mandatory = true
versionRange = "[3.1.4-beta,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.tfcm]]
modId = "forge"
mandatory = true
versionRange = "[47.1.3,47.1.6),[47.1.81,47.2.0),[47.2.6,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.tfcm]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.20.2)"
ordering = "AFTER"
side = "BOTH"
